import Link from 'next/link'
import PageIntro from '../../components/PageIntro'
import PageShell from '../../components/PageShell'

const offers = [
  { title: 'Prototype printing', text: 'Turn a CAD file into a physical test part, enclosure, bracket, or teaching model.', meta: 'FDM · PLA / PETG' },
  { title: 'Design for print', text: 'Get help preparing geometry, tolerances, supports, and orientation before material is wasted.', meta: 'Consultancy · From NPR 2,500' },
  { title: 'Small-batch parts', text: 'Repeatable print runs for fixtures, replacement parts, classroom sets, and maker products.', meta: 'Quote by volume' },
]

export default function PrintingPage() {
  return <PageShell><PageIntro eyebrow="3D printing · new vertical" title="From a sketch to a thing you can hold." body="GENUM is adding print-to-order fabrication for Nepal makers, students, product teams, and classrooms. Start with a file, a reference object, or a rough idea." /><section className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-4 lg:grid-cols-3">{offers.map((offer) => <article key={offer.title} className="border-t-2 border-ink bg-white p-6"><p className="text-xs font-black uppercase tracking-widest text-cobalt">{offer.meta}</p><h2 className="mt-12 font-display text-2xl font-bold">{offer.title}</h2><p className="mt-3 leading-7 text-slate-600">{offer.text}</p><Link href="/contact" className="mt-7 inline-block rounded-full bg-cobalt px-5 py-3 text-sm font-black text-white">Request a quote ↗</Link></article>)}</div><div className="mt-12 grid gap-8 border-y border-line py-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.24em] text-cobalt">The workflow</p><h2 className="mt-3 font-display text-3xl font-bold">A useful loop, not a mystery box.</h2></div><ol className="grid gap-4 sm:grid-cols-2"><li className="border-l-2 border-signal pl-4"><strong>01 · Share</strong><p className="mt-1 text-sm leading-6 text-slate-600">Send an STL, STEP, sketch, or reference.</p></li><li className="border-l-2 border-signal pl-4"><strong>02 · Review</strong><p className="mt-1 text-sm leading-6 text-slate-600">We check fit, material, supports, and finish.</p></li><li className="border-l-2 border-signal pl-4"><strong>03 · Print</strong><p className="mt-1 text-sm leading-6 text-slate-600">You approve the estimate before the machine starts.</p></li><li className="border-l-2 border-signal pl-4"><strong>04 · Learn</strong><p className="mt-1 text-sm leading-6 text-slate-600">Get the part plus notes for the next iteration.</p></li></ol></div><div className="mt-10 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-ink p-7 text-white"><div><p className="text-xs font-black uppercase tracking-widest text-signal">Shop materials</p><h2 className="mt-2 font-display text-2xl font-bold">Keep the workshop moving.</h2></div><Link href="/products" className="rounded-full bg-signal px-5 py-3 text-sm font-black text-ink">Browse 3D supplies ↗</Link></div></section></PageShell>
}
