import { roboticsProducts } from './robotics-catalog'

export type Product = {
  id: string
  name: string
  category: string
  price: number
  priceLabel: string
  sku: string
  productType: 'Retail kit' | 'Project package' | 'Material' | 'Service package'
  note: string
  description: string
  specs: string[]
  audience: string
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced' | 'Professional'
  warranty: string
  stock: number
  delivery: string
  color: string
  badge?: string
}

export const products: Product[] = [
  { id: 'esp32-car', name: 'ESP32 Modular Car', category: 'Robotics', price: 4850, priceLabel: 'NPR 4,850', sku: 'GEN-ROB-ESP32-001', productType: 'Retail kit', note: 'Build, code, and explore', description: 'A modular two-wheel platform for learning wireless control, sensors, and the joy of making something move because you told it to.', specs: ['ESP32 development board', '2WD acrylic chassis', 'Ultrasonic distance sensor', 'USB-C power and Nepali quickstart guide'], audience: 'Students, makers, and beginner robotics learners', difficulty: 'Beginner', warranty: '7-day component replacement for manufacturing defects', stock: 12, delivery: 'Ships in 1–2 working days', color: 'from-[#dfeaff] to-[#9fbaff]', badge: 'Bestseller' },
  { id: 'sensor-kit', name: 'Everyday Sensor Kit', category: 'Electronics', price: 2200, priceLabel: 'NPR 2,200', sku: 'GEN-ELC-SENS-001', productType: 'Retail kit', note: '15 hands-on experiments', description: 'A tidy collection of the sensors and modules that turn a breadboard into a small laboratory.', specs: ['15 sensor modules', 'Breadboard and jumper wires', 'Project card deck', 'Compatible with Arduino and ESP32'], audience: 'Schools, hobbyists, and electronics learners', difficulty: 'Beginner', warranty: '7-day component replacement for manufacturing defects', stock: 24, delivery: 'Ships in 1–2 working days', color: 'from-[#e8f3ef] to-[#a9d9c6]' },
  { id: 'starter-robot', name: 'RoboStart Classroom Kit', category: 'Learning', price: 6900, priceLabel: 'NPR 6,900', sku: 'GEN-LRN-ROBO-001', productType: 'Retail kit', note: 'Ages 10+ · Nepali guide', description: 'A classroom-friendly robotics kit made for first principles: assemble, program, test, and explain what happened.', specs: ['Modular robot base', 'Line tracking sensors', 'Visual coding cards', 'Teacher guide in English and Nepali'], audience: 'Schools, clubs, and learners aged 10+', difficulty: 'Beginner', warranty: '30-day support for kit assembly and setup', stock: 8, delivery: 'Dispatches in 3–5 working days', color: 'from-[#fff1cf] to-[#f1c875]', badge: 'New' },
  { id: 'motor-pack', name: 'Precision Motor Pack', category: 'Components', price: 890, priceLabel: 'NPR 890', sku: 'GEN-CMP-MOTO-001', productType: 'Retail kit', note: 'Reliable motion, ready to wire', description: 'A matched pair of compact geared motors for prototypes that need repeatable, dependable motion.', specs: ['2 × geared DC motors', '3–6V operating range', 'Mounting hardware', 'Bench-tested before dispatch'], audience: 'Robotics builders and repair projects', difficulty: 'Intermediate', warranty: '7-day component replacement for manufacturing defects', stock: 37, delivery: 'Ships next working day', color: 'from-[#f1e9ff] to-[#c4a8ef]' },
  { id: 'edge-ai-lab', name: 'Edge AI Vision Lab', category: 'AI + IoT', price: 9800, priceLabel: 'NPR 9,800 · pre-order', sku: 'GEN-AIO-EDGE-001', productType: 'Retail kit', note: 'See, measure, decide locally', description: 'A practical computer-vision lab for learning how sensors, tiny models, and edge devices work together without sending every frame to the cloud.', specs: ['Camera-enabled edge board', 'LED and distance sensor pack', 'Model deployment walkthrough', 'Responsible AI project guide'], audience: 'Intermediate learners and prototype teams', difficulty: 'Intermediate', warranty: 'Support terms confirmed at launch', stock: 0, delivery: 'Pre-order opening soon · Q4 2026', color: 'from-[#dce8ff] to-[#7e9ff2]', badge: 'Coming soon' },
  { id: 'iot-field-lab', name: 'IoT Field Lab', category: 'AI + IoT', price: 7600, priceLabel: 'NPR 7,600 · pre-order', sku: 'GEN-AIO-FIELD-001', productType: 'Retail kit', note: 'From sensor to useful signal', description: 'A long-running sensor project for understanding connectivity, data quality, dashboards, and decisions grounded in the physical world.', specs: ['Temperature and humidity sensors', 'Low-power connectivity board', 'Dashboard starter project', 'Data ethics and reliability checklist'], audience: 'Students, researchers, and IoT teams', difficulty: 'Intermediate', warranty: 'Support terms confirmed at launch', stock: 0, delivery: 'Pre-order opening soon · Q4 2026', color: 'from-[#dff4ec] to-[#79c7a8]', badge: 'Coming soon' },
  { id: 'pla-filament', name: 'PLA Maker Filament · 1 kg', category: '3D Printing', price: 2850, priceLabel: 'NPR 2,850', sku: 'GEN-3DP-PLA-001', productType: 'Material', note: 'Reliable prints, clean finish', description: 'Everyday PLA filament for prototypes, enclosures, classroom parts, and the small idea that needs a physical form.', specs: ['1.75 mm diameter', '1 kg spool', 'Low-odor PLA material', 'Suggested nozzle temperature: 195–215°C'], audience: 'FDM printer owners and maker spaces', difficulty: 'Beginner', warranty: 'Replacement review for sealed-product defects', stock: 14, delivery: 'Ships in 1–2 working days', color: 'from-[#ffe3d6] to-[#f1a17e]', badge: 'Maker essential' },
  { id: 'reprap-service-kit', name: '3D Printer Care Kit', category: '3D Printing', price: 1650, priceLabel: 'NPR 1,650', sku: 'GEN-3DP-CARE-001', productType: 'Retail kit', note: 'Keep the next layer honest', description: 'A practical maintenance kit for calibration, cleaning, and the small repairs that keep an FDM printer useful.', specs: ['Nozzle cleaning needles', 'Brass brush and tweezers', 'Bed leveling cards', 'PTFE tube and cutter'], audience: 'FDM printer owners and workshop operators', difficulty: 'Intermediate', warranty: 'Replacement review for sealed-product defects', stock: 9, delivery: 'Ships in 1–2 working days', color: 'from-[#e9e0ff] to-[#b79be9]' },
  { id: 'home-automation-package', name: 'Home Automation Starter Package', category: 'Project Solutions', price: 18500, priceLabel: 'From NPR 18,500', sku: 'GEN-PRJ-HOME-001', productType: 'Project package', note: 'Control, schedule, and understand your space', description: 'A scoped starter package based on the portfolio home automation system, with connected controls, schedules, and energy visibility.', specs: ['Requirements workshop', 'Controller and relay prototype', 'Mobile/web control concept', 'Basic documentation and handover'], audience: 'Homes, offices, and demonstration spaces', difficulty: 'Professional', warranty: '30-day post-delivery support; final terms in proposal', stock: 0, delivery: 'Quote and site review required · typical 2–4 weeks', color: 'from-[#fff1cf] to-[#f1c875]' },
  { id: 'wireless-sensor-network-package', name: 'Wireless Sensor Network Package', category: 'Project Solutions', price: 14500, priceLabel: 'From NPR 14,500', sku: 'GEN-PRJ-SENS-001', productType: 'Project package', note: 'Measure the environment with confidence', description: 'A pilot package based on the portfolio wireless sensor network, covering node planning, sensor integration, connectivity, and reporting.', specs: ['Pilot architecture', 'Up to 3 sensor nodes', 'Connectivity and data plan', 'Dashboard proof of concept'], audience: 'Agriculture, labs, and facilities teams', difficulty: 'Advanced', warranty: '30-day pilot support; final terms in proposal', stock: 0, delivery: 'Discovery required · typical 3–6 weeks', color: 'from-[#e8f3ef] to-[#a9d9c6]' },
  { id: 'smart-street-lighting-package', name: 'Smart Street Lighting Pilot', category: 'Project Solutions', price: 85000, priceLabel: 'From NPR 85,000', sku: 'GEN-PRJ-LIGHT-001', productType: 'Project package', note: 'Adaptive lighting with visibility', description: 'A pilot package based on the portfolio smart street lighting network, including sensing, adaptive control, remote monitoring, and reporting.', specs: ['Pilot design and site review', 'Up to 5 controlled light points', 'Motion/ambient sensing concept', 'Fault alert dashboard prototype'], audience: 'Municipalities, campuses, and facilities', difficulty: 'Professional', warranty: 'Final warranty depends on installed hardware and proposal', stock: 0, delivery: 'Site survey required · quote by scope', color: 'from-[#f1a17e] to-[#e9c16a]' },
  { id: 'smart-agriculture-package', name: 'Smart Agriculture Pilot', category: 'Project Solutions', price: 65000, priceLabel: 'From NPR 65,000', sku: 'GEN-PRJ-AGRI-001', productType: 'Project package', note: 'Turn field signals into better decisions', description: 'A pilot package based on the portfolio smart agriculture platform, combining soil monitoring, irrigation logic, and field reporting.', specs: ['Field requirements review', 'Soil moisture and climate sensors', 'Irrigation automation pilot', 'Dashboard and handover guide'], audience: 'Farms, research teams, and agri-businesses', difficulty: 'Professional', warranty: 'Final warranty depends on environmental conditions and proposal', stock: 0, delivery: 'Site review required · typical 4–8 weeks', color: 'from-[#dff4ec] to-[#79c7a8]' },
  { id: 'rfid-parking-package', name: 'RFID Parking Management Pilot', category: 'Project Solutions', price: 95000, priceLabel: 'From NPR 95,000', sku: 'GEN-PRJ-PARK-001', productType: 'Project package', note: 'Make access and availability visible', description: 'A pilot package based on the portfolio intelligent parking system, covering access control, occupancy visibility, and operational reporting.', specs: ['Workflow and site review', 'RFID/NFC access concept', 'Availability dashboard prototype', 'Integration plan and documentation'], audience: 'Campuses, offices, and managed parking sites', difficulty: 'Professional', warranty: 'Final warranty depends on installed hardware and proposal', stock: 0, delivery: 'Site review required · quote by scope', color: 'from-[#dce8ff] to-[#7e9ff2]' },
  ...roboticsProducts,
]

export const formatNPR = (value: number) => `NPR ${value.toLocaleString('en-IN')}`
export const findProduct = (slug: string) => products.find((product) => product.id === slug)
