export type QuotationItem = [type: string, variant: string, description: string, suppliers: string]

export const quotationItems: QuotationItem[] = [
  ['Air Quality', 'MQ135 Gas Sensor', 'Detects air quality and harmful gases for smart-city nodes', 'Himalayan Solution'],
  ['Arduino Boards', 'Arduino Uno R3', 'Widely used AVR-based development board for prototyping', 'Himalayan Solution; Botyards'],
  ['Arduino Boards', 'Arduino Mega 2560', 'Large-pin-count board for projects needing many I/O lines', 'Himalayan Solution'],
  ['Arduino Boards', 'Arduino Nano', 'Compact breadboard-friendly Arduino compatible board', 'Botyards; Himalayan Solution'],
  ['Arduino Boards', 'Arduino Pro Micro', 'Small ATmega32U4-based board with native USB support', 'Local resellers'],
  ['Arduino Boards', 'Arduino Leonardo', 'AVR board with native USB HID capabilities', 'Himalayan Solution'],
  ['Arduino Boards', 'Arduino Due', '32-bit ARM-based Arduino for higher-performance tasks', 'Specialized suppliers'],
  ['Battery', 'LiPo 3S 2200mAh', 'Common drone battery for small to medium multirotors', 'Battery shops'],
  ['Battery', 'Li-ion 18650 Pack 3.7V x N', 'Custom battery packs for robots and power banks', 'Local battery assemblers'],
  ['Breadboard', 'Full-size Solderless Breadboard', 'Prototyping board for wiring circuits without soldering', 'Himalayan Solution'],
  ['Camera', 'OV2640 2MP Camera Module', 'Small camera module used with ESP32-CAM and microcontrollers', 'Botyards'],
  ['Charge Controller', 'MPPT 10A', 'Efficient solar charge controller for battery charging', 'Solar suppliers'],
  ['Charging Modules', 'TP4056 1S Li-ion Charger', 'Single-cell linear charger with micro-USB input and protection', 'Himalayan Solution; Botyards'],
  ['Charging Modules', '2S Balance Charger Module', 'Two-cell Li-ion/LiPo balance charging board for safe charging', 'Battery shops; Supreme Light'],
  ['Charging Modules', '3S Balance Charger Module', 'Three-cell balance charger for multi-cell packs', 'Supreme Light'],
  ['Charging Modules', 'BMS Protection Board 1S-4S', 'Battery management system for overcharge/discharge protection', 'Himalayan Solution; battery suppliers'],
  ['Charging Modules', 'USB LiPo Charger with Protection', 'Compact charger board with integrated protection and USB input', 'Botyards'],
  ['Charging Modules', 'Wireless Charging Module', 'Qi-compatible modules for contactless charging of small devices', 'Specialized electronics sellers'],
  ['Connecting Cables', 'Jumper Wires Male-Male', 'Breadboard jumper wires for prototyping connections', 'Himalayan Solution; Botyards'],
  ['Connecting Cables', 'Jumper Wires Male-Female', 'For connecting modules to breadboards and headers', 'Local electronics stores'],
  ['Connecting Cables', 'Dupont Ribbon Cable 10/20 Pin', 'Multi-conductor ribbon for parallel signal wiring', 'Himalayan Solution'],
  ['Connecting Cables', 'USB Cables Type-A to Micro USB', 'Standard USB cable for power and data to many modules', 'Botyards; general stores'],
  ['Connecting Cables', 'USB Type-C Cables', 'Modern reversible USB cable for newer devices and power delivery', 'Local electronics shops'],
  ['Connecting Cables', 'JST-SM 2/3/4 Pin Cables', 'Locking connector cables for sensors, LEDs and small motors', 'Himalayan Solution; Supreme Light'],
  ['Connecting Cables', 'IDC Ribbon Cable with IDC Connector', 'Flat ribbon cable for multi-pin board-to-board connections', 'Botyards'],
  ['DC to DC Converter', 'Buck LM2596 Adjustable', 'Step-down regulator module for converting higher DC to lower DC', 'Supreme Light; Himalayan Solution'],
  ['DC to DC Converter', 'Boost MT3608 Adjustable', 'Step-up regulator for raising voltage from lower DC sources', 'Botyards; Himalayan Solution'],
  ['DC to DC Converter', 'Buck-Boost Module', 'Module that can both step-up and step-down depending on input', 'Supreme Light'],
  ['DC to DC Converter', '5V Regulator Module', 'Fixed 5V regulator modules for powering microcontrollers', 'Local power module vendors'],
  ['DC to DC Converter', '3.3V Regulator Module', 'Fixed 3.3V modules for sensors and low-voltage logic', 'Himalayan Solution'],
  ['DC to DC Converter', 'High Current Buck Module', 'Heavy-duty buck for motor and high-load power supplies', 'Supreme Light'],
  ['Display', '16x2 Character LCD', 'Alphanumeric LCD for simple text output with HD44780-compatible interface', 'Himalayan Solution; Botyards; Supreme Light'],
  ['Display', '20x4 Character LCD', 'Larger character LCD for multi-line text displays', 'Himalayan Solution; Botyards'],
  ['Display', '0.96-inch OLED I2C', 'Small monochrome OLED with I2C interface for compact graphical output', 'Himalayan Solution; local sellers'],
  ['Display', '1.3-inch OLED SPI', 'Higher resolution monochrome OLED using SPI for faster updates', 'Himalayan Solution'],
  ['Display', '1.8-inch TFT SPI', 'Color TFT display for basic graphics, SPI interface', 'Botyards; Supreme Light'],
  ['Display', '2.4-inch TFT Touch', 'Color TFT with resistive touch for simple GUIs', 'Himalayan Solution; Supreme Light'],
  ['Display', '3.5-inch TFT Touch', 'Larger touch display for richer interfaces and panels', 'Supreme Light; Himalayan Solution'],
  ['Display', '7-Segment LED Module', 'Numeric LED modules for counters and clocks', 'Local electronics shops'],
  ['Display', 'Dot Matrix LED Module', 'Matrix LED for text/graphics and simple animations', 'Botyards; Himalayan Solution'],
  ['Encoder', 'Optical Rotary Encoder', 'High-resolution encoder for wheel odometry and motor feedback', 'Supreme Light'],
  ['Encoder Wheel', 'Magnetic Hall Encoder Wheel', 'Wheel-mounted encoder for odometry and closed-loop control', 'Supreme Light'],
  ['ESC', '30A BLHeli ESC', 'Brushless ESC for quadcopters and multirotors', 'Drone shops'],
  ['ESP Boards', 'ESP8266 NodeMCU', 'Wi-Fi development board with USB interface for IoT projects', 'Himalayan Solution; Botyards'],
  ['ESP Boards', 'Wemos D1 Mini', 'Compact ESP8266 board for space-constrained IoT devices', 'Himalayan Solution'],
  ['ESP Boards', 'ESP32 WROOM', 'Dual-core Wi-Fi and Bluetooth module for advanced IoT applications', 'Himalayan Solution; Supreme Light'],
  ['ESP Boards', 'ESP32-S3', 'ESP32 variant with improved AI acceleration and USB support', 'Himalayan Solution'],
  ['ESP Boards', 'ESP32-CAM', 'ESP32 module with onboard camera for vision and streaming projects', 'Botyards; Himalayan Solution'],
  ['Flight Controller', 'Pixhawk Cube', 'Advanced autopilot for professional drones and UAVs', 'Drone suppliers'],
  ['Frame', 'Quadcopter Frame 250mm/450mm', 'Structural frame for building multirotor drones', 'Drone suppliers'],
  ['Gimbal', '3-Axis Brushless Gimbal', 'Stabilizes camera for smooth aerial footage', 'Himalayan Solution'],
  ['GPS', 'u-blox NEO-M8N', 'High-accuracy GPS module for outdoor navigation', 'Himalayan Solution'],
  ['GSM Module', 'SIM800L GSM/GPRS', 'Cellular connectivity for remote control and telemetry', 'Botyards'],
  ['Header Pins', 'Male Straight Header Single Row', 'Standard straight male header for PCB connections', 'Himalayan Solution; Botyards'],
  ['Header Pins', 'Male Right Angle Header', 'Right-angle male header for edge connections on PCBs', 'Local electronics stores'],
  ['Header Pins', 'Female Header Single Row', 'Female socket headers for plug-in modules and shields', 'Himalayan Solution'],
  ['Header Pins', 'Stackable Header', 'Tall stackable headers for shield stacking on Arduino boards', 'Botyards'],
  ['Header Pins', 'Double Row Header', 'Two-row header for modules requiring multiple pins in compact layout', 'Himalayan Solution'],
  ['Heat Shrink', 'Assorted Heat Shrink Tubing', 'Insulation and strain relief for wire joints', 'Local suppliers'],
  ['IMU', 'BNO055 Absolute Orientation', 'Sensor with onboard fusion for simplified orientation data', 'Himalayan Solution'],
  ['IMU', 'ICM20948 9-axis', 'High-performance 9-axis IMU for advanced stabilization', 'Botyards'],
  ['Linear Actuator', '12V 100mm Stroke', 'Compact linear actuator for gates, grippers and automation', 'Supreme Light'],
  ['LoRa Module', 'SX1278 433/868/915MHz', 'Long-range low-power radio for remote IoT nodes', 'Himalayan Solution'],
  ['MCU', 'STM32F4 Discovery Board', '32-bit MCU board for real-time control and motor tasks', 'Specialized sellers'],
  ['Motor Driver', 'L298N Dual H-Bridge', 'Classic dual H-bridge for small DC motors and simple robot drives', 'Himalayan Solution'],
  ['Motor Driver', 'TB6612FNG Dual Motor Driver', 'Efficient dual motor driver for low-voltage DC motors', 'Botyards'],
  ['Motors', 'DC Brushed 130', 'Small low-power DC motor for toys and small robots', 'Supreme Light; local markets'],
  ['Motors', 'DC Brushed 180', 'Medium small DC motor with higher torque than 130 series', 'Supreme Light'],
  ['Motors', 'DC Brushed 390', 'Common hobby motor for small robots and mechanisms', 'Himalayan Solution'],
  ['Motors', 'DC Brushed 775', 'High-power DC motor for heavy loads and high RPM applications', 'Supreme Light'],
  ['Motors', 'N20 Geared DC', 'Micro geared motor with integrated gearbox for torque and slow speed', 'Himalayan Solution; Botyards'],
  ['Motors', 'Metal Gear DC Motor', 'Durable geared motors with metal gears for higher load', 'Supreme Light'],
  ['Motors', 'Micro Servo SG90', 'Lightweight micro servo for small linkages and hobby projects', 'Himalayan Solution; Botyards'],
  ['Motors', 'Standard Servo MG996R', 'High torque servo for robotics arms and steering mechanisms', 'Supreme Light; Himalayan Solution'],
  ['Motors', 'Stepper 28BYJ-48', 'Unipolar stepper with gearbox for precise low-cost positioning', 'Botyards; Himalayan Solution'],
  ['Motors', 'Stepper NEMA17', 'Standard bipolar stepper for CNC and 3D printers', 'Supreme Light; local suppliers'],
  ['Motors', 'BLDC 2212', 'Brushless motor commonly used in drones and high-efficiency drives', 'Drone shops; Supreme Light'],
  ['Motors', 'Planetary Gear Motor', 'Compact high-torque geared motor for precision robotics', 'Himalayan Solution'],
  ['Multimeter', 'Digital Multimeter 600V/10A', 'Measurement tool for voltage, current and continuity', 'Tool shops; Himalayan Solution'],
  ['Nuts and Bolts', 'M2 Screw and Nut Assortment', 'Small machine screws and nuts for PCB mounting and small assemblies', 'Hardware stores; Himalayan Solution'],
  ['Nuts and Bolts', 'M2.5 Screw and Nut Assortment', 'Slightly larger screws for medium-small assemblies', 'Local hardware stores'],
  ['Nuts and Bolts', 'M3 Screw and Nut Assortment', 'Common size for mounting motors, standoffs and brackets', 'Supreme Light; hardware stores'],
  ['Nuts and Bolts', 'M4 Screw and Nut Assortment', 'Larger fasteners for structural parts and motor mounts', 'Hardware stores'],
  ['Nuts and Bolts', 'Brass Standoffs and Spacers', 'PCB standoffs in various lengths for mounting and isolation', 'Himalayan Solution; Botyards'],
  ['Nuts and Bolts', 'Nylon Nuts and Washers', 'Insulating fasteners and washers for electrical isolation', 'Local suppliers'],
  ['Nuts and Bolts', 'Self Tapping Screws Assortment', 'Screws for plastic and sheet metal assembly without nuts', 'Hardware stores; electronics shops'],
  ['PCB Service', 'Custom PCB Prototype', 'Small-run PCB fabrication and assembly services', 'Local PCB houses'],
  ['PDB', '4-6S Power Distribution Board', 'Distributes battery power to ESCs and peripherals on drones', 'Drone shops'],
  ['pH Sensor', 'Analog pH Probe Kit', 'pH measurement for hydroponics and soil testing', 'Himalayan Solution'],
  ['PID Controller', 'Self-balancing controller board', 'Dedicated board for two-wheel self-balancing robots', 'Himalayan Solution'],
  ['PID Tuning Kit', 'Autotune Module / Software Tools', 'Tools and modules to tune PID loops for balancing and control', 'Himalayan Solution'],
  ['Power Bank', '10,000-20,000 mAh', 'Portable USB power for SBCs and field devices', 'General electronics stores'],
  ['Propellers', '5x3 6x4 8x4.5 Propellers', 'Prop sizes for different drone motors and thrust needs', 'Drone shops'],
  ['Rain Sensor', 'Rain Detection Module', 'Detects rainfall for weather stations and irrigation control', 'Local electronics shops'],
  ['Relay Module', '4-Channel 5V Relay Module', 'Electrically isolated relay board for AC/DC switching', 'Himalayan Solution'],
  ['RTC', 'DS3231 High-Precision RTC', 'Accurate real-time clock module for scheduled tasks', 'Himalayan Solution'],
  ['SBC', 'Raspberry Pi 4 4GB', 'Single-board computer for vision, ML and automation tasks', 'Local resellers'],
  ['SBC Accessory', 'Raspberry Pi Camera V2', 'High-quality camera for Pi-based vision projects', 'Himalayan Solution'],
  ['SD Module', 'MicroSD Card Module SPI', 'Data logging and storage for MCUs and SBCs', 'Botyards'],
  ['Smart Switch', 'Sonoff Basic / Tasmota', 'Wi-Fi smart switch for remote control of AC loads', 'Himalayan Solution'],
  ['Soil Sensor', 'Capacitive Soil Moisture Sensor', 'Reliable soil moisture sensing for irrigation automation', 'Agricultural suppliers'],
  ['Solar Panel', '50W Polycrystalline Panel', 'Small solar panel for remote sensors and charging', 'Solar suppliers'],
  ['Soldering Kit', '60W Soldering Iron + Accessories', 'Essential kit for assembly and repairs', 'Tool shops'],
  ['Solenoid Valve', '12V DC Solenoid Valve', 'Electrically actuated valve for irrigation and fluid control', 'Agricultural suppliers'],
  ['SSR', 'Solid State Relay 25A', 'Silent switching for AC loads in automation systems', 'Local electronics shops'],
  ['Stepper Driver', 'A4988 Stepper Driver', 'Microstepping driver for bipolar stepper motors', 'Himalayan Solution'],
  ['Stepper Driver', 'DRV8825 Stepper Driver', 'Higher-current stepper driver with finer microstepping', 'Supreme Light'],
  ['TDS Sensor', 'Water TDS Sensor Module', 'Measures total dissolved solids for water quality', 'Botyards'],
  ['Voltage Sensor', 'INA219 I2C Current/Voltage', 'High-side current and power monitoring over I2C', 'Himalayan Solution'],
  ['Water Pump', 'Submersible 12V Pump', 'Small pump for irrigation, fountains and water transfer', 'Hardware stores'],
  ['Wheels', 'Rubber Robot Wheel 65mm', 'Standard rubber wheel for small robot chassis with hub bore', 'Himalayan Solution; Botyards'],
  ['Wheels', 'Rubber Robot Wheel 90mm', 'Larger rubber wheel for medium-sized platforms', 'Supreme Light; hardware stores'],
  ['Wheels', 'Omni Wheel 60mm', 'Multi-directional wheel for holonomic drive systems', 'Himalayan Solution'],
  ['Camera', 'OV5640 5MP Camera Module', 'Higher-resolution camera for ESP32-S3 vision projects and streaming', 'Botyards'],
  ['Display', 'TM1637 4-Digit 7-Segment Display', 'Clock-style numeric display module with integrated driver for counters', 'Local electronics shops'],
  ['Encoder', 'AS5600 Magnetic Encoder', '12-bit contactless rotary position sensor for precision motor feedback', 'Himalayan Solution'],
  ['IMU', 'BMI270 6-axis IMU', 'Low-noise 6-axis inertial measurement unit for stabilized platforms', 'Specialized sellers'],
  ['Motors', 'SG90 Micro Servo Single', 'Single micro servo motor for small positioning and steering tasks', 'Botyards'],
  ['Relay Module', '8-Channel 5V Relay Module', 'Eight-channel relay board for complex multi-device automation setups', 'Himalayan Solution'],
  ['ESP Boards', 'ESP32-S2 Mini', 'Compact single-core ESP32 with USB OTG for space-constrained IoT builds', 'Himalayan Solution'],
  ['Smart Switch', 'Sonoff TH10 Wi-Fi Relay', 'Temperature and humidity triggered smart switch for environmental control', 'Local electronics shops'],
  ['Camera', 'ESP32-CAM-MB Programmer', 'USB programmer board for flashing and debugging ESP32-CAM modules', 'Botyards'],
  ['Display', 'MAX7219 LED Matrix Module', 'Cascadable 8x8 LED dot matrix for scrolling text and animations', 'Himalayan Solution'],
  ['GPS', 'BN-220 GPS Module with Antenna', 'Compact GPS receiver with patch antenna for outdoor navigation and tracking', 'Himalayan Solution'],
]
