import PageIntro from '../../components/PageIntro'
import PageShell from '../../components/PageShell'

const labs = [
	['12 Oct 2026', 'Robotics with ESP32', 'Build a working machine and learn the loop: assemble, program, test, explain.'],
	['26 Oct 2026', 'Sensors to decisions', 'A practical IoT lab covering data quality, connectivity, dashboards, and useful alerts.'],
	['02 Nov 2026', 'Design for 3D printing', 'Turn a rough idea into a printable part while learning tolerances, supports, material, and iteration.'],
	['09 Nov 2026', 'Human-centered AI starter', 'Understand model limits, evaluation, privacy, and where a person should stay in the loop.'],
]

export default function TrainingPage() {
	return <PageShell><PageIntro eyebrow="Training & consultancy · 2026" title="Learn by making the thing." body="Workshops, labs, and technical guidance for schools, teams, and independent builders. Every session ends with something tested, not just something discussed." /><section className="mx-auto max-w-7xl px-5 py-14 lg:px-8"><div className="grid gap-4 lg:grid-cols-3">{labs.map(([date, title, text]) => <article key={title} className="rounded-2xl bg-ink p-7 text-white"><p className="text-xs font-black uppercase tracking-widest text-signal">{date}</p><h2 className="mt-12 font-display text-2xl font-bold">{title}</h2><p className="mt-3 leading-7 text-blue-100/70">{text}</p><a href="/contact" className="mt-8 inline-block rounded-full bg-signal px-5 py-3 text-sm font-black text-ink">Register interest ↗</a></article>)}</div><div className="mt-12 grid gap-8 border-y border-line py-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-black uppercase tracking-[.24em] text-cobalt">Workshop module · ESP32 car</p><h2 className="mt-3 font-display text-3xl font-bold">Build a browser-controlled robot.</h2><p className="mt-4 leading-7 text-slate-600">The migrated workshop curriculum covers an ESP32 web server, local WiFi control, L298N motor driving, speed commands, and a five-second automatic stop when commands disappear.</p></div><div><p className="text-xs font-black uppercase tracking-widest text-cobalt">Hardware checklist</p><ul className="mt-4 grid gap-2 text-sm text-slate-600 sm:grid-cols-2"><li>ESP32 DevKit</li><li>L298N motor driver</li><li>Two 3–12V DC motors</li><li>7.4–12V battery pack</li><li>2.4GHz WiFi network</li><li>Arduino IDE 2.x</li></ul></div></div><div className="mt-12 border-l-2 border-signal pl-5"><p className="max-w-3xl leading-7 text-slate-600">Our format follows a simple principle: technology should expand human capability. We make room for critical thinking, safety, ethics, and local-language explanation alongside the hardware.</p><a href="https://www.unesco.org/en/digital-education" className="mt-3 inline-block text-sm font-bold text-cobalt underline underline-offset-4">See UNESCO’s digital education guidance ↗</a></div></section></PageShell> 
}
